version: "3.8"

services:
  app:
    build: ../
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://psql-db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
    depends_on:
      - db
  db:
    image: postgres
    container_name: psql-db
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - /pg/data:/var/lib/postgresql/data

volumes:
  pg_data: